### ISSUE TITLE
Outdated theme 2021

### ISSUE THREAD

**Issue by w4ld0j** [obscuredetour/odin-project-dark#1]
Hi, it seems that your dark theme has some areas where it is difficult to read in 2021.
I don't know much about css but I have added this lines in order to make it legible.

```css
.user-project-submissions__title, .user-project-submissions__blank-slate-message, .skills__title, 
.skills__content, .lesson-content details summary, .card-secondary__prerequisites, p, .advert__pitch, 
.advert__icon-text
{
    color: #bfbfbf;
}
    
.internal-link
{
    color: #cc9543;
}
```

By the way thank you, it looks really nice.
